# -*- coding: utf-8 -*-
# Conteudo do checklist da Bruna. ('q')=pergunta com linha  ('n')=nota de padrao Valvic
SECOES = [
("Informações gerais do projeto", [
 ('q',"Projeto está na versão final, aprovada pelo cliente?"),
 ('q',"As medidas apresentadas são de obra ou de projeto?"),
 ('q',"Pé-direito final confirmado?"),
 ('q',"Níveis de piso acabado confirmados?"),
 ('q',"Existem rodapés, boiseries, molduras, sancas ou outros elementos que interfiram na marcenaria?"),
 ('q',"Existem paredes, pilares, vigas ou shafts que precisam ser considerados?"),
 ('q',"Há alguma parede fora de esquadro ou condição especial identificada?"),
 ('q',"Existe alguma alteração de obra ainda prevista?"),
]),
("Materiais e acabamentos", [
 ('q',"MDF especificado: fabricante, linha e cor?"),
 ('q',"Acabamento interno dos móveis definido?"),
 ('n',"Espessuras das chapas seguem o padrão Valvic."),
 ('q',"Sentido dos veios definido?"),
 ('n',"Continuidade de veios entre portas e gavetas é padrão da casa."),
 ('q',"Há lâmina natural, madeira maciça, pintura, laca ou outro acabamento especial?"),
 ('q',"Vidros: comum, extra clear, reflecta, fumê, bronze, canelado?"),
 ('q',"Espessura dos vidros?"),
 ('q',"Espelhos: comum, bronze, fumê?"),
 ('q',"Perfis metálicos: modelo, acabamento e cor?"),
 ('q',"Existe Corstone, palha, tela, couro, tecido, pedra ou outro material especial? Especificar exatamente."),
]),
("Portas e frentes", [
 ('q',"Tipo de abertura de cada porta definido?"),
 ('q',"Portas de abrir, correr, basculantes, articuladas ou retráteis?"),
 ('q',"Puxador definido? Cava, perfil, usinado, alça, ponto ou fecho toque?"),
 ('q',"Sentido de abertura das portas indicado?"),
 ('q',"Dobradiças especiais?"),
 ('q',"Amortecimento?"),
 ('q',"Portas com recorte ou usinagem?"),
 ('q',"Frisos: largura, profundidade e espaçamento?"),
 ('q',"Portas ripadas: largura e espaçamento dos ripados?"),
 ('q',"Alguma porta precisa abrir 180°?"),
 ('q',"Alguma abertura interfere em parede, puxador, eletrodoméstico ou outro móvel?"),
]),
("Gavetas e ferragens", [
 ('q',"Quantidade e altura das gavetas confirmadas?"),
 ('q',"Tipo de corrediça definido?"),
 ('q',"Corrediça oculta ou telescópica?"),
 ('q',"Com amortecimento ou toque?"),
 ('q',"Capacidade de carga necessária?"),
 ('q',"Gavetas internas dentro de gavetões?"),
 ('q',"Divisórias ou organizadores internos?"),
 ('q',"Gavetas para joias, acessórios, talheres?"),
 ('q',"Ferragens específicas definidas por marca e modelo?"),
]),
("Interiores dos armários", [
 ('q',"Distribuição interna totalmente definida?"),
 ('q',"Altura das prateleiras?"),
 ('q',"Prateleiras fixas ou reguláveis?"),
 ('q',"Quantidade de prateleiras?"),
 ('q',"Cabideiros simples ou duplos?"),
 ('q',"Altura dos cabideiros?"),
 ('q',"Nichos com dimensões definidas?"),
 ('q',"Maleiros?"),
 ('q',"Sapateiras?"),
 ('q',"Cofre ou compartimento especial?"),
 ('q',"Há equipamentos que precisam ficar dentro do móvel?"),
]),
("Iluminação", [
 ('q',"Existe LED na marcenaria?"),
 ('q',"Localização exata das fitas e perfis?"),
 ('q',"Perfil embutido ou sobreposto?"),
 ('q',"Temperatura de cor: 2700K, 3000K ou 4000K?"),
 ('q',"Acionamento: interruptor, sensor, presença, abertura de porta, touch?"),
 ('q',"Fonte e driver ficarão onde?"),
 ('q',"Existe acesso para manutenção da fonte?"),
 ('q',"Ponto elétrico está previsto?"),
 ('q',"Passagem de fiação está definida?"),
 ('q',"Perfil de LED deve ficar aparente ou oculto?"),
 ('q',"Há iluminação em prateleiras, nichos, cabideiros ou cristaleiras?"),
]),
("Elétrica, hidráulica e infraestrutura", [
 ('q',"Tomadas dentro ou sobre a marcenaria?"),
 ('q',"Alturas e posições confirmadas?"),
 ('q',"Interruptores interferindo no móvel?"),
 ('q',"Pontos de TV e internet?"),
 ('q',"Passagem de cabos?"),
 ('q',"Pontos hidráulicos?"),
 ('q',"Registros precisam permanecer acessíveis?"),
 ('q',"Sifão interfere em gavetas ou prateleiras?"),
 ('q',"Gás?"),
 ('q',"Ar-condicionado?"),
 ('q',"Grelhas e retornos de ar?"),
 ('q',"Quadros elétricos?"),
 ('q',"Algum ponto precisa receber tampa ou acesso técnico na marcenaria?"),
]),
("Eletrodomésticos e equipamentos", [
 ('q',"Marca e modelo de TODOS os eletrodomésticos definidos?"),
 ('q',"Ficha técnica disponível?"),
 ('q',"Cafeteira ou equipamentos embutidos?"),
 ('q',"Ventilação mínima exigida pelo fabricante considerada?"),
 ('q',"Folgas para instalação e manutenção consideradas?"),
 ('q',"Portas e gavetas conseguem abrir sem interferência?"),
 ('q',"Tomadas estão compatíveis com os equipamentos?"),
]),
("Bancadas e pedras", [
 ('q',"Quem instala primeiro: a pedra ou a marcenaria?"),
 ('q',"Existe apoio da pedra sobre a marcenaria?"),
 ('q',"Há necessidade de reforço estrutural?"),
 ('q',"Encontro entre pedra e MDF definido?"),
]),
("Painéis de TV", [
 ('q',"Modelo e tamanho da TV?"),
 ('q',"Suporte da TV?"),
 ('q',"Altura do centro da TV?"),
 ('q',"Soundbar?"),
 ('q',"Decodificador, videogame ou roteador?"),
 ('q',"Localização dos equipamentos?"),
 ('q',"Acesso para manutenção?"),
 ('q',"Ventilação dos equipamentos?"),
 ('q',"Painel removível?"),
 ('q',"Tomadas ficarão ocultas?"),
]),
("Banheiros", [
 ('q',"Cuba e bancada definidas?"),
 ('q',"Sifão considerado?"),
 ('q',"Gavetas precisam de recorte para o sifão?"),
 ('q',"Tipo de cuba?"),
 ('q',"Rodabanca?"),
 ('q',"Espelho faz parte da marcenaria?"),
 ('q',"Tomadas dentro do armário?"),
 ('q',"Há umidade direta próxima ao móvel?"),
]),
("Cabeceiras e quartos", [
 ('q',"Medida da cama?"),
 ('q',"Tomadas e interruptores na cabeceira?"),
 ('q',"Cabeceira estofada?"),
 ('q',"Tecido especificado?"),
 ('q',"Painéis até o teto ou com altura determinada?"),
]),
("Instalação e encontros", [
 ('q',"Móvel vai até o teto?"),
 ('n',"Se vai até o teto: o fechamento de teto segue o padrão Valvic, especificado na folha técnica."),
 ('n',"Sóculo segue o padrão Valvic."),
 ('q',"Portas e janelas possuem espaço suficiente para abertura?"),
]),
]
FECHAMENTO = [
 "Largura × altura × profundidade de cada módulo",
 "Espessura de cada peça quando não for padrão",
 "Cotas internas importantes",
 "Frisos",
 "Usinagens",
 "Raios e curvas",
 "Ângulos",
 "Sentido dos veios",
 "Sentido de abertura",
 "Ferragens especiais",
 "Encontros entre materiais",
 "Fixação de peças suspensas",
 "Cargas especiais",
 "Detalhes construtivos fora do padrão",
]
